[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor --chip esp32"

[build]
rustflags = [
  "-C", "force-frame-pointers",
  "-C", "link-arg=-Tlinkall.x",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
